
[package]
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]
description = "GIT virtualization proxy"
edition = "2018"
keywords = ["git", "monorepo", "workflow", "scm"]
license-file = "LICENSE"
name = "josh-proxy"
readme = "README.md"
repository = "https://github.com/esrlabs/josh"
version = "0.3.0"


[dependencies]
clap = "2.33"
futures = "0.3"
tokio = { version = "1.4", features = ["full"] }
hyper = { version = "0.14", features = ["stream"] }
hyper_cgi = "0.1"
hyper-staticfile = "*"
hyper-tls = "*"
toml = "0.5"
git2 = { git = "https://github.com/initcrash/git2-rs.git", default-features = false}
tracing = { version = "0.1", features = ["max_level_trace", "release_max_level_trace"] }
tracing-futures = "0.2"
tracing-subscriber = "0.2"
tracing-opentelemetry = "0.11"
opentelemetry = "0.13"
opentelemetry-jaeger = "0.12"
reqwest= { version = "0.11", default-features = false, features = ["blocking", "json"] }
uuid = { version = "0.8", features = ["v4"] }
base64 = "0.13"
regex = "1.4"
lazy_static = "1.4"
josh = {path = "../"}
serde_json= "1.0"
serde= "*"
rust-crypto = "0.2"
unindent = "*"
juniper = "*"
url = "*"
percent-encoding = "*"
