language: rust
rust:
  - stable
  - beta
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - pip install 'cram' --user
  - cargo install hyper_cgi --features=test-server
script:
  - export CARGO_TARGET_DIR=`pwd`/target
  - git config --global init.defaultBranch master
  - cargo build --all
  - cram tests/**/*.t
notifications:
  email:
    on_success: never
os:
  - linux
dist: focal
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - git
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - tree
